apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ include "pheweb.fullname" . }}
spec:
  capacity:
      storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.persistentVolume.path }}
    server: {{ .Values.persistentVolume.server }}
