apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ include "pheweb.fullname" . }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
